SELECT AN.ANIMALNAME, MD.MEDICINENAME, md.expirationdate , TR.DOCTORID FROM ANIMAL AN
       INNER JOIN USEIN UI ON UI.MEDICALFILEID = AN.MEDICALFILEID
       INNER JOIN MEDICINE MD ON UI.MEDICINEID = MD.MEDICINEID
       INNER JOIN TREATMENT TR ON TR.MEDICALFILEID = AN.MEDICALFILEID
       WHERE (MD.EXPIRATIONDATE < sysdate) 
