SELECT A.ANIMALNAME, BN.BINOMIALNOMENCLATURENAME FROM ANIMAL A
INNER JOIN BINOMIALNOMENCLATURE BN
      ON BN.BINOMIALNOMENCLATUREID = A.BINOMIALNOMENCLATUREID
      WHERE A.AREACONDITIONID = 95 -- AREACONDITION IS JUNGLE
